export const ActionType ={
    GET_ALL_CHARACTER :"GET_ALL_CHARACTER" ,
    INC_PAGE_NUMBER:"INC_PAGE_NUMBER",
    DEC_PAGE_NUMBER:"DEC_PAGE_NUMBER",
    SET_STATUS: "SET_STATUS",
    SET_GENDER: "SET_GENDER",
    SET_SPECIES: "SET_SPECIES",
    SEARCHED_CHARACTER: "SEARCHED_CHARACTER",
    FAVORITE_CHARACTER:"FAVORITE_CHARACTER",
    ADD_FAV_NAME:"ADD_FAV_NAME",
    GET_FAV_CHARACTER:"GET_FAV_CHARACTER"
    }